

%Run somaDetectionTests.m

%Create mag4 struct
mag4.root = '';
mag4.prefix ='';
mag4.bbox = ''; % same that you chose for somaDetectionTests.m

% read segIds from the Knossos cubes generated by somaDetectionTests.m
segIds = determineSegIdsFromMag4(p,mag4);

% Some segIDs may be empty
segIdsEmpty = cellfun(@isempty,segIds);
segIds(segIdsEmpty)=[];

save([p.saveFolder 'nucleiSegIds.mat'],'segIds');
