before_script:
  - echo -e "[url \"git@gitlab.mpcdf.mpg.de:\"]\n insteadOf = \"https://gitlab.mpcdf.mpg.de/\"" > ~/.gitconfig
  - git submodule update --init --recursive 

tests:
  script:
    - matlab -nosplash -nodisplay -r "runAllTests();"
