before_script:
  - echo -e "Host gitlab.mpcdf.mpg.de\n  IdentityFile /var/lib/gitlab-ci/gitlab-ci" > ~/.ssh/config
  - echo -e "[url \"git@gitlab.mpcdf.mpg.de:\"]\n insteadOf = \"https://gitlab.mpcdf.mpg.de/\"" > ~/.gitconfig
  - git submodule update --init --recursive 

tests:
  script:
    - matlab -nosplash -nodisplay -r "runAllTests();"
