function job = agglomerateDirectionalitySuperStart(startagglo, axonProbThreshold, outputfolder)


    functionH = @connectEM.agglomerateDirectionalitySuper;
    inputCell = cellfun(@(x){x}, num2cell(1:200), 'uni', 0);
    sharedInputs = {false, startagglo, axonProbThreshold, outputfolder};
    cluster = Cluster.getCluster( ...
        '-pe openmp 1', ...
        '-p -100', ...
        '-l h_vmem=24G', ...
        '-l s_rt=23:50:00', ...
        '-l h_rt=24:00:00');
    job = Cluster.startJob( functionH, inputCell, ...
        'name', 'directionality', ...
        'sharedInputs', sharedInputs, ...
        'sharedInputsLocation', [2, 3, 4, 5], ...
        'cluster', cluster);

end
