function job = agglomerateDirectionalitySuperStart()


    functionH = @(x)connectEM.agglomerateDirectionalitySuper(x, false);
    inputCell = {num2cell(1:200)};
    cluster = Cluster.getCluster( ... 
        '-pe openmp 1', ... 
        '-p -300', ...
        '-l h_vmem=24G', ... 
        '-l s_rt=23:50:00', ... 
        '-l h_rt=24:00:00');
    job = Cluster.startJob( functionH, inputCell, ...
        'name', 'directionality', ...
        'cluster', cluster);

end

