function job = buildIsosurfaceOfAggloStart(p, outputFolder, segIds, namePrefix)

    fileNames = arrayfun(@(x)[namePrefix num2str(x) '.ply'], 1:length(segIds), 'uni', 0)';
    functionH = @connectEM.buildIsosurfaceOfAgglo;
    inputCell = cellfun(@(x,y){x y}, segIds, fileNames, 'uni', 0);
    sharedInputs = {p};
    job = Cluster.startJob( functionH, inputCell, ...
                'name', 'isosurfacesFromAgglo', ...
                'sharedInputs', sharedInputs, ...
                'sharedInputsLocation', 1, ...
                'cluster', '-l h_vmem=12G');
end

