function debugNewQueries(segmentMeta, agglos, q, outputFolder)
    % Visualize a set of agglomerates and queries generated by/from them 

    theseNodes = {};
    theseNames = {};
    theseComments = {};
    for i=1:length(agglos)
        theseNodes{end} = segments.point(:,agglos{i})'; 
        theseNames{end} = [num2str(i, '%.3i') '_agglomerate'];
        theseComments{end} = {};
        for j=1:2
            % Write queries indicating direction (and comment to paste behing link for flight location)
            theseNodes{end+1}(1,:) = round(q.pos{i}(j,:));
            theseNodes{end}(2,:) = round(q.pos{i}(j,:) + 10 * q.dir{idx(i)}(j,:));
            theseNames{end+1} = [num2str(i, '%.3i') '_query ' num2str(j)];
            if q.excluded{i}(j)
                theseNames{end} = [theseNames{end} '_excluded'];
            end
            theseComments{end+1}{2} = ['#' num2str(q.pos{idx(i)}(j,1)) ',' num2str(q.pos{idx(i)}(j,2)) ',' num2str(q.pos{idx(i)}(j,3)) ',' ...
                '1,2,' num2str(q.angles(1)) ',' num2str(q.angles(2)) ',' num2str(q.angles(3))];
        end
    end
    generateSkeletonFromNodes([outputFolder datestr(clock, 30) '_skel.nml'], theseNodes, theseNames, theseComments); 
end
