function job = generateDendriteQueriesStart


    functionH = @connectEM.generateDendriteQueries;
    inputCell = cellfun(@(x){x}, num2cell(1000:1999), 'uni', 0);
    cluster = Cluster.getCluster( ...
        '-pe openmp 1', ...
        '-p -100', ...
        '-l h_vmem=66G', ...
        '-l s_rt=23:50:00', ...
        '-l h_rt=24:00:00');
    job = Cluster.startJob( functionH, inputCell, ...
        'name', 'directionality', ...
        'cluster', cluster);

end
function dummy()
end
