addpath('/gaba/u/kboerg/code/manuelCode/games') %for a clean version of findCCaccordingToGraph
functionH = @connectEM.makeSkelForChiasmataDetection;
inputCell = cellfun(@(x){x}, num2cell(2 : 501), 'uni', 0);
cluster = Cluster.getCluster( ...
    '-pe openmp 1', ...
    '-p 0', ...
    '-l h_vmem=24G', ...
    '-l s_rt=23:50:00', ...
    '-l h_rt=24:00:00');
job = Cluster.startJob( functionH, inputCell, ...
    'name', 'chiasmata', ...
    'cluster', cluster);
    
% the giant super agglo should run locally
connectEM.makeSkelForChiasmataDetection(1);