function job = predictDataset(p)
    taskArgs = arrayfun( ...
        @(local) {local.saveFolder}, ...
        p.local(:), 'UniformOutput', false);
    job = startCPU( ...
        @connectEM.predictLocalCube, taskArgs, ...
        'neuriteContinuityPrediction');
end

