function classifier = trainClassifier( trainFeatures, trainLabels )
%Fit a classifier based on given training features and labels

classifier = fitensemble( ...
    trainFeatures, trainLabels, ...
    'LogitBoost', 1500, 'tree', ...
    'LearnRate', 0.1, ...
    'NPrint', 100, ...
    'Prior', 'Empirical', ...
    'Type', 'Classification', ...
    'ClassNames', [1 -1]);

end
