function job = graphConstruction(parameter)
    % collect parameters
    cubeCount = numel(parameter.local);
    inputCell = cell(cubeCount, 1);

    for curIdx = 1:cubeCount
        curCube = parameter.local(curIdx);
        curSegFile = [curCube.saveFolder, 'segGlobal.mat'];
        mask = readKnossosRoi(regexprep(parameter.raw.root,'/color/','/mask/'),[parameter.raw.prefix,'_mask'],curCube.bboxSmall);
        if all(mask(:))  % ignore mask if everythin is zero (no padded area)
            inputCell{curIdx} = { ...
                curSegFile, ...
                curCube.edgeFile, ...
                curCube.borderFile, ...
                curCube.segmentFile};
        else
            inputCell{curIdx} = { ...
                curSegFile, ...
                curCube.edgeFile, ...
                curCube.borderFile, ...
                curCube.segmentFile, ...
                ~mask};
        end
    end

    functionH = @findEdgesAndBordersWrapper;
    job = startCPU(functionH, inputCell, 'graphConstruction', 24);
end

