function job = graphConstruction(parameter)
    % collect parameters
    cubeCount = numel(parameter.local);
    inputCell = cell(cubeCount, 1);
    for curIdx = 1:cubeCount
        curCube = parameter.local(curIdx);
        curSegFile = [curCube.saveFolder, 'segGlobal.mat'];
        if isfield(parameter,'mask') % check for mask data
	   inputCell{curIdx} = { ...
                curSegFile, ...
                curCube.edgeFile, ...
                curCube.borderFile, ...
                curCube.segmentFile, ...
                parameter.mask,curCube.bboxSmall};
 
        else
	    inputCell{curIdx} = { ...
                curSegFile, ...
                curCube.edgeFile, ...
                curCube.borderFile, ...
                curCube.segmentFile};

        end
    end
    functionH = @findEdgesAndBordersWrapper;
    job = startCPU(functionH, inputCell, 'graphConstruction', 12); % 30 min should suffice
end

