function job = miniSegmentation(p)
    inputCell = arrayfun( ...
        @(local) { ...
            p.class, local.bboxBig, ...
            p.seg.func, local.tempSegFile}, ...
        p.local(:), 'UniformOutput', false);
    
    job = Cluster.startJob( ...
        @segmentForPipeline, inputCell, ...
        'name', 'segmentation', ...
        'cluster', { ...
            'memory', 36, ...
            'time', '24:00:00'});
end
