% Written by
%   Alessandro Motta <alessandro.motta@brain.mpg.de>
clear;

%% Configuration
datasetName = 'H2_3_v2_U1_SubI';
%% Loading data
rootDir = ['/tmpscratch/sahilloo/data/' datasetName '/pipelineRun_mr2e_wsmrnet/'];
load(fullfile(rootDir,'allParameter.mat'))
param = p;

% output folder for saving new agglomeration state
outDir = fullfile(p.saveFolder, 'tracings', 'typeEM');
if ~exist(outDir, 'dir')
    mkdir(outDir);
end

% NOTE(amotta): Random boxes #1, #14, and #5 are the ones handed out to
% HiWis for volume annotations. I've also used them to generate ConnectEM
% training data.
%   Subsequently, the remaining random boxes (as generated by
% L23.Scripts.buildRandomBoxes 7a79056c3c7dc3fb96e3f83314d12b7596a2fdda)
% were appended to this list. Some random boxes (e.g., number 4) were
% skipped if they were dominated by somatic volume.

boxesWk = [ ...
    9120, 6595, 2982, 267, 267, 108; ...
    11599, 7708, 2779, 267, 267, 108;...
    3846, 3961, 2655,267, 267, 108;...
    4832, 9134, 721, 267, 267, 108;...
    6921, 6313, 1203, 267, 267, 108;,...
    7947, 7742, 407,  267, 267, 108;...
    8011, 11459, 1829, 267, 267, 108;...
    5431, 11002, 928, 267, 267, 108;...
    6481, 9049, 1342, 267, 267, 108];

sampleRange = [1, 200];

info = Util.runInfo();
Util.showRunInfo(info);

segPoints = Seg.Global.getSegToPointMap(param);

%% Sample edges
clear cur*:

for curBoxIdx = 1:size(boxesWk, 1)
    curBoxWk = boxesWk(curBoxIdx, :);
    curBox = Util.convertWebknossosToMatlabBbox(curBoxWk);
    
    curSegIds = loadSegDataGlobal(param.seg, curBox);
    curSegIds = reshape(setdiff(curSegIds, 0), [], 1);
    
    curRange = min(sampleRange, numel(curSegIds));
    curRange = curRange(1):curRange(2);
    
    rng(0);
    curRandIds = randperm(numel(curSegIds));
    curRandIds = curSegIds(curRandIds(curRange));
    
    curDigits = ceil(log10(1 + numel(curRandIds)));
    
    curNames = arrayfun( ...
        @(idx, id) sprintf('%0*d. Segment %d', curDigits, idx, id), ...
        1:numel(curRandIds), reshape(curRandIds, 1, []), ...
        'UniformOutput', false);
    curNodes = segPoints(curRandIds, :);
    
    curSkel = skeleton();
    curSkel = Skeleton.setParams4Pipeline(curSkel, param);
    curSkel = Skeleton.setDescriptionFromRunInfo(curSkel, info);
    
    curSkel = curSkel.addNodesAsTrees(curNodes);
    curSkel.names = reshape(curNames, [], 1);
    
    curSkel.write(fullfile(outDir, sprintf('box-%d.nml', curBoxIdx)));
end
