function axonClasses = buildAxonClasses(conn, varargin)
    % axonClasses = buildAxonClasses(conn, varargin)
    %
    % Written by
    %   Alessandro Motta <alessandro.motta@brain.mpg.de>
    opts = struct;
    opts.minSynPre = 1;
    opts = Util.modifyStruct(opts, varargin{:});
    
    conn.axonMeta.spineSynFrac = ...
        conn.axonMeta.spineSynCount ...
        ./ conn.axonMeta.synCount;

    axonClasses = struct;
    axonClasses(1).axonIds = find( ...
        conn.axonMeta.synCount >= opts.minSynPre ...
      & conn.axonMeta.spineSynFrac > 0.7);
    axonClasses(1).poissAxonIds = ...
        axonClasses(end).axonIds;
    axonClasses(1).title = sprintf( ...
       ['axons with ≥ %d synapses and ', ...
        'at least 70 %% onto spines (n = %d)'], ...
        opts.minSynPre, numel(axonClasses(end).axonIds));

    axonClasses(2).axonIds = find( ...
        conn.axonMeta.synCount >= opts.minSynPre ...
      & conn.axonMeta.spineSynFrac < 0.3);
    axonClasses(2).poissAxonIds = ...
        axonClasses(end).axonIds;
    axonClasses(2).title = sprintf( ...
       ['axons with ≥ %d synapses and ', ...
        'at most 30 %% onto spines (n = %d)'], ...
        opts.minSynPre, numel(axonClasses(end).axonIds));

    axonClasses(3).axonIds = find( ...
        conn.axonMeta.isThalamocortical);
    axonClasses(3).poissAxonIds = find( ...
        conn.axonMeta.synCount >= opts.minSynPre ...
      & conn.axonMeta.spineSynFrac > 0.7);
    axonClasses(3).title = sprintf( ...
        'thalamocortical axons (n = %d)', ...
        numel(axonClasses(end).axonIds));
end