function job = runFixMasks(p, newClassRoot)
    % job = runFix(p, newPrefix)
    %   Applies `Myelin.enforceMyelinMasks` to the entire dataset.
    %   For further information, check out the documentation of said
    %   function.
    %
    % Written by
    %   Alessandro Motta <alessandro.motta@brain.mpg.de>
    %   Sahil Loomba <sahil.loomba@brain.mpg.de>

    taskInputArguments = arrayfun( ...
        @(local) {newClassRoot, local.bboxSmall}, ...
        p.local(:), 'UniformOutput', false);
    
    job = Cluster.startJob( ...
        @Myelin.enforceMyelinMasks, ...
        taskInputArguments, ...
        'sharedInputs', {p}, ...
        'name', 'myelinFix', ...
        'cluster', { ...
            'memory', 12, ...
            'time', '12:00:00'});
end
