% Written by
%   Alessandro Motta <alessandro.motta@brain.mpg.de>
clear;

%% Configuration
rootDir = '/gaba/u/mberning/results/pipeline/20170217_ROI';
connFile = fullfile(rootDir, 'connectomeState', 'connectome_axons-19-a_dendrites-wholeCells-03-v2-classified_spine-syn-clust.mat');

minSynPre = 10;

info = Util.runInfo();

%% Loading data
param = load(fullfile(rootDir, 'allParameter.mat'));
param = param.p;

[conn, syn, axonClasses] = connectEM.Connectome.load(param, connFile);

%% Prepare data
axonMeta = conn.axonMeta;
axonMeta.fullPriSpineSynFrac = ...
    axonMeta.fullPriSpineSynCount ...
 ./ axonMeta.fullSynCount;

axonMeta.fullSecSpineSynFrac = ...
    axonMeta.fullSpineSynCount ...
  - axonMeta.fullPriSpineSynCount;
axonMeta.fullSecSpineSynFrac = ...
    axonMeta.fullSecSpineSynFrac ...
 ./ axonMeta.fullSynCount;

excSomaIds = find( ...
    conn.denMeta.targetClass == 'Somata' ...
  & not(conn.denMeta.isInterneuron));

excSomaConn = conn.connectome;
excSomaConn(~ismember(excSomaConn.edges(:, 2), excSomaIds), :) = [];
excSomaConn.synCount = cellfun(@numel, excSomaConn.synIdx);

axonMeta.excSomaSynFrac = accumarray( ...
    excSomaConn.edges(:, 1), ...
    excSomaConn.synCount, ...
   [height(conn.axonMeta), 1]);
axonMeta.excSomaSynFrac = ...
    axonMeta.excSomaSynFrac ...
 ./ axonMeta.synCount;

axonMeta(axonMeta.synCount < minSynPre, :) = [];

%% Prepare for plot
colors = get(groot, 'defaultAxesColorOrder');
axonMeta.color = repmat(colors(1, :), height(axonMeta), 1);

excMask = ...
    axonMeta.fullPriSpineSynFrac ...
  > axonMeta.fullSecSpineSynFrac;
axonMeta.color(excMask, :) = repmat(colors(2, :), sum(excMask), 1);

%% Plot
fig = figure();
fig.Color = 'white';
fig.Position(3:4) = [675, 330];

ax = subplot(1, 2, 1);
scatter(ax, ...
    axonMeta.fullPriSpineSynFrac, ...
    axonMeta.excSomaSynFrac, ...
    36, axonMeta.color, '.');
xlabel(ax, {'Fraction of synapses being'; 'primary spine innervations'});
ylabel(ax, {'Fraction of synapses'; 'onto excitatory somata'});

ax = subplot(1, 2, 2);
scatter(ax, ...
    axonMeta.fullPriSpineSynFrac, ...
    axonMeta.fullSecSpineSynFrac, ...
    36, axonMeta.color, '.');
ylabel(ax, {'Fraction of synapses being'; 'secondary spine innervations'});

set(fig.Children, ...
    'XLim', [0, 1], ...
    'YLim', [0, 1], ...
    'TickDir', 'out', ...
    'PlotBoxAspectRatio', [1, 1, 1], ...
    'DataAspectRatioMode', 'auto');

annotation( ...
    fig, ...
    'textbox', [0, 0.9, 1, 0.1], ...
	'String', {info.filename; info.git_repos{1}.hash}, ...
    'EdgeColor', 'none', 'HorizontalAlignment', 'center');
