

%Run somaDetectionTests.m

%Create mag4 struct for nuclei or vessel mag4 cubes
mag4.root = '';
mag4.prefix ='';
mag4.bbox = ''; %Choose the Bbox chosen for nuclei detection and on which segmenttion was done p.bbox (not p.bbox_wK)

% read segIds from the Knossos cubes generated by somaDetectionTests.m
segIds = determineSegIdsFromMag4(p,mag4);

% Some segIDs may be empty
segIdsEmpty = cellfun(@isempty,segIds);
segIds(segIdsEmpty)=[];

Util.save([p.saveFolder 'nucleiSegIds.mat'],segIds); % ...if mag4 was for nuclei. Change to vesselSegIds if mag4 was for vessels
