% TODO(amotta)
% * convert into function
% * get rid of magic numbers
% * update to new signature of `borderCalc`

mkdir('/tmpscratch/kboerg/borders3/')
functionH = @connectEM.borders.borderCalc;
inputCell = cellfun(@(x){x}, num2cell(1:(11*17*13)), 'uni', 0);
cluster = Cluster.getCluster( ...
    '-pe openmp 1', ...
    '-p 0', ...
    '-l h_vmem=48G', ...
    '-l s_rt=23:50:00', ...
    '-l h_rt=24:00:00');
job = Cluster.startJob( functionH, inputCell, ...
    'name', 'borders', ...
    'cluster', cluster);