function job = startGPU(fH, iC, jN);
    % Wrapper function for startJob.m used for backward compability
    
    clusterGPU = Cluster.getCluster( ...
        '-pe openmp 1', ...
        '-p 0', ...
        '-l h_vmem=36G', ...
        '-l s_rt=23:50:00', ...
        '-l h_rt=24:00:00', ...
        '-l num_k40=1');

    job = Cluster.startJob(clusterGPU, fH, iC, 'name', jN);

end

